### ISSUE TITLE
List of radio station directories

### ISSUE THREAD

**Issue by UC3829** [dersphere/plugin.audio.radio_de#10]
http://www.talkstreamlive.com/
http://radio-locator.com/
http://www.radioguide.fm/
http://www.onlineradiostations.com/
http://www.internet-radio.com/

http://qualisoft.dk/
- http://www.radiotunes.com/
- http://www.di.fm/

http://thebatplayer.fm
- http://www.shoutcast.com/
- http://www.1.fm
- http://www.di.fm/
- http://live365.com/
- http://tunein.com/
- http://www.radionomy.com

http://8tracks.com/
http://pureplayradio.com/
http://www.accuradio.com

**Comment by dersphere** [comment]
Sorry, this add-on does not directly manage the listed radio stations. Instead it is an unofficial client for radio.net
If you want to add stations please contact them
