### ISSUE TITLE
Browser interface for adding custom stations

### ISSUE THREAD

**Issue by UC3829** [dersphere/plugin.audio.radio_de#12]
Implement a back end web server on Kodi, so user-created streams can be added to "My Stations" through a web browser interface.  (Like **The Bat Player** on Roku & Apple TV).

http://thebatplayer.fm

See also:

https://addons.mozilla.org/en-US/firefox/addon/send-to-xbmc
https://github.com/dirkjanm/firefox-send-to-xbmc

https://chrome.google.com/webstore/detail/play-to-kodi/fncjhcjfnnooidlkijollckpakkebden
https://github.com/khloke/play-to-xbmc-chrome/wiki/Getting-Started

**Comment by dersphere** [comment]
Sorry, I dont have enough spare time to implement something like this.
