### ISSUE TITLE
Add cache busting/redetection of stations

### ISSUE THREAD

**Issue by pgcd** [dersphere/plugin.audio.radio_de#16]
On my system, there seem to be some stations that seem either down or always playing the same track - DW's Langsam Gesprochene Nachrichten is stuck somewhere in 2014, RBB Inforadio is completely down, Kulturradio plays a message about a change of address etc.
I have checked on radio.de and they all seem to be working fine, so I think the problem might be somewhere around the plugin - my first impression is that there is some unexpected (by me) caching going on so the station data does not get correctly updated on startup. 
Any ideas?

**Comment by dersphere** [comment]
You should find details in the kodi.log if there is any cache in place. You can also upload it anywhere and add a link here so I can tell.

**Comment by pgcd** [comment]
Looks like the problem is a bit more complicated: here's the log (more details after)
`
16:25:34.235 T:140523738228480  NOTICE: [xbmcswift2] Request for "/" matches rule for function "show_root_menu"
16:25:38.939 T:140523738228480  NOTICE: [xbmcswift2] Request for "/stations/city/" matches rule for function "show_station_categories"
16:25:38.939 T:140523738228480  NOTICE: [plugin.audio.radio_de] get_categories started with category_type=city
16:25:38.939 T:140523738228480  NOTICE: [plugin.audio.radio_de] __api_call started with path=menu/valuesofcategory, param={'category': '_city'}
16:25:38.939 T:140523738228480  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/menu/valuesofcategory?category=_city
16:25:43.298 T:140523738228480  NOTICE: [xbmcswift2] Request for "/stations/city/Berlin/" matches rule for function "show_stations_by_category"
16:25:43.298 T:140523738228480  NOTICE: [plugin.audio.radio_de] get_stations_by_category started with category_type=city, category_value=Berlin
16:25:43.299 T:140523738228480  NOTICE: [plugin.audio.radio_de] get_category_types started
16:25:43.299 T:140523738228480  NOTICE: [plugin.audio.radio_de] __api_call started with path=menu/broadcastsofcategory, param={'category': '_city', 'value': 'Berlin'}
16:25:43.299 T:140523738228480  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/menu/broadcastsofcategory?category=_city&value=Berlin
16:25:44.451 T:140523738228480  NOTICE: [plugin.audio.radio_de] __add_stations started with 576 items
16:25:53.805 T:140523963893504   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/35/74/14429/t100.png
16:25:53.808 T:140523738228480   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/41/4a/3561/t100.png
16:25:54.061 T:140523963893504   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/ec/8b/2879/t100.png
16:25:54.625 T:140523335632640   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/10/13/4635/t100.png
16:25:54.947 T:140523335632640   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/33/ed/14320/t100.png
16:26:00.438 T:140523268470528   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/1f/30/14441/t100.png
16:26:01.178 T:140523268470528   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/43/c6/5583/t100.png
16:26:01.559 T:140523335632640   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/dd/37/18295/t100.png
16:26:01.816 T:140523963893504   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/ef/fb/14350/t100.png
16:26:09.061 T:140523738228480   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/1d/07/4785/t100.png
16:26:42.094 T:140523963893504   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/23/67/15534/t100.png
16:26:44.356 T:140523963893504   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/ed/9c/15109/t100.png
16:26:44.573 T:140523335632640   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/b6/cc/15627/t100.png
16:26:45.182 T:140523268470528   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/e5/46/4245/t100.png
16:26:49.239 T:140523738228480   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/c4/57/4989/t100.png
16:26:51.411 T:140523738228480   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/ed/9c/15109/t100.png
16:26:51.411 T:140523963893504   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/b6/cc/15627/t100.png
16:26:51.427 T:140523335632640   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/e5/46/4245/t100.png
16:26:57.218 T:140523268470528   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/b6/cc/15627/t100.png
16:26:57.219 T:140523738228480   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://static.rad.io/images/broadcasts/ed/9c/15109/t100.png
16:27:01.663 T:140523385997056  NOTICE: [xbmcswift2] Request for "/station/2260" matches rule for function "get_stream_url"
16:27:01.663 T:140523385997056  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=2260
16:27:01.663 T:140523385997056  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '2260'}
16:27:01.664 T:140523385997056  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/broadcast/getbroadcastembedded?broadcast=2260
16:27:01.981 T:140523385997056  NOTICE: [plugin.audio.radio_de] __follow_redirect probing url=http://addrad.io/4WRKnk
16:27:02.747 T:140523385997056  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://rbb-inforadio-live.cast.addradio.de/rbb/inforadio/live/mp3/128/stream.mp3?ar-distributor=f0a0
16:27:18.306 T:140522748122880  NOTICE: [xbmcswift2] Request for "/" matches rule for function "show_root_menu"
16:27:33.070 T:140522748122880  NOTICE: [xbmcswift2] Request for "/station/2260" matches rule for function "get_stream_url"
16:27:33.081 T:140522748122880  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=2260
16:27:33.081 T:140522748122880  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '2260'}
16:27:33.082 T:140522748122880  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/broadcast/getbroadcastembedded?broadcast=2260
16:27:33.285 T:140522748122880  NOTICE: [plugin.audio.radio_de] __follow_redirect probing url=http://addrad.io/4WRKnk
16:27:33.713 T:140522748122880  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://rbb-inforadio-live.cast.addradio.de/rbb/inforadio/live/mp3/128/stream.mp3?ar-distributor=f0a0
16:27:45.343 T:140523142584064  NOTICE: [xbmcswift2] Request for "/station/10303" matches rule for function "get_stream_url"
16:27:45.344 T:140523142584064  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=10303
16:27:45.344 T:140523142584064  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '10303'}
16:27:45.344 T:140523142584064  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/broadcast/getbroadcastembedded?broadcast=10303
16:27:45.800 T:140523142584064  NOTICE: [plugin.audio.radio_de] __resolve_playlist started with station=10303
16:27:45.800 T:140523142584064  NOTICE: [plugin.audio.radio_de] __resolve_playlist found .xml file
16:27:45.800 T:140523142584064  NOTICE: [plugin.audio.radio_de] __resolve_playlist found 1 servers
16:27:45.801 T:140523142584064  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://radio-download.dw.com/Events/dwelle/dira/mp3/deutschkurse/langsamenachrichten/D32C50F0_2.mp3
16:28:50.681 T:140523419580160  NOTICE: [xbmcswift2] Request for "/" matches rule for function "show_root_menu"
16:28:54.769 T:140523419580160  NOTICE: [xbmcswift2] Request for "/stations/search/" matches rule for function "search"
16:29:19.164 T:140523419580160  NOTICE: [xbmcswift2] Request for "/stations/search/langsam/" matches rule for function "search_result"
16:29:19.164 T:140523419580160  NOTICE: [plugin.audio.radio_de] search_stations_by_string started with search_string=langsam
16:29:19.165 T:140523419580160  NOTICE: [plugin.audio.radio_de] __api_call started with path=index/searchembeddedbroadcast, param={'q': 'langsam', 'start': '0', 'rows': '10000', 'streamcontentformats': 'aac,mp3'}
16:29:19.165 T:140523419580160  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/index/searchembeddedbroadcast?q=langsam&start=0&rows=10000&streamcontentformats=aac%2Cmp3
16:29:19.339 T:140523419580160  NOTICE: [plugin.audio.radio_de] __add_stations started with 4 items
16:29:24.342 T:140523385997056  NOTICE: [xbmcswift2] Request for "/station/10303" matches rule for function "get_stream_url"
16:29:24.343 T:140523385997056  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=10303
16:29:24.343 T:140523385997056  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '10303'}
16:29:24.343 T:140523385997056  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/broadcast/getbroadcastembedded?broadcast=10303
16:29:24.653 T:140523385997056  NOTICE: [plugin.audio.radio_de] __resolve_playlist started with station=10303
16:29:24.653 T:140523385997056  NOTICE: [plugin.audio.radio_de] __resolve_playlist found .xml file
16:29:24.654 T:140523385997056  NOTICE: [plugin.audio.radio_de] __resolve_playlist found 1 servers
16:29:24.657 T:140523385997056  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://radio-download.dw.com/Events/dwelle/dira/mp3/deutschkurse/langsamenachrichten/D32C50F0_2.mp3
`
So, ironically enough, when I tried right now, RBB started working again - which I guess means the problem was upstream.
On the other hand, the issue persists with DW's Nachrichten - the stream is actually from October 2016, and from the URL in the log I suspect the problem is again with radio.de rather than the plugin. 
Still, maybe there's something that can be changed in the API call to ensure the stream is the current one (the one that plays on radio.de, I mean).

**Comment by dersphere** [comment]
No client side cache (kodi or the add-on) takes place. So if old streams are played nothing I can do against :(
