### ISSUE TITLE
Codec issue at OpenElec on RaspberryPI 2

### ISSUE THREAD

**Issue by motorradfahrer** [dersphere/plugin.audio.radio_de#8]
Hi, 
I did already leave comments at the Kodi Nerds forum for two of your great addons but you might be for a longer time not there and I noticed you did here during the last days some updates.
I did already use in the past the radio addon at Windows. Now I tried at the weekend for the first time at OpenElec. I did only found one radio station which I was able to start (FFH). The other ones did display at the log file a codec issue. Perhaps you have an idea how to solve it. Here is what I found at the log:

get_stream_url result: br_mp3-bayern3_m.akacast.akamaistream.net/7/442/142692/v1/gnl.akacast.akamaistream.net/br_mp3_bayern3_m
18:47:25 T:1969643520 ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for br_mp3-bayern3_m.akacast.akamaistream.net/7/442/142692/v1/gnl.akacast.akamaistream.net/br_mp3_bayern3_m
18:47:30 T:1969643520 ERROR: CAudioDecoder: Unable to Init Codec while loading file br_mp3-bayern3_m.akacast.akamaistream.net/7/442/142692/v1/gnl.akacast.akamaistream.net/br_mp3_bayern3_m
18:47:30 T:1969643520 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
18:47:30 T:1969643520 ERROR: Playlist Player: skipping unplayable item: 10, path [plugin://plugin.audio.radio_de/station/2247]

Kind Regards

**Comment by dersphere** [comment]
This has something to do with openelec, curl and the stream server.
Details here: https://github.com/OpenELEC/OpenELEC.tv/issues/3900

In short, just wait for a new openelec version.
